version = 1

[global]
dll = "/home/slamzdank/Games/Game Utilities/Lossless Scaling/Lossless.dll"

[[game]]
exe = "GameThread"
multiplier = 3
flow_scale = 0.85
performance_mode = true
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "Hi-Fi-RUSH.exe"
multiplier = 3
flow_scale = 0.85
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "StarRail.exe"
multiplier = 3
flow_scale = 0.85
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "ZenlessZoneZero"
multiplier = 3
flow_scale = 0.85
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "benchmark"
multiplier = 4
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "eldenring.exe"
multiplier = 3
flow_scale = 0.85
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "vkcube"
multiplier = 4
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "chiaki"
multiplier = 2
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"
